before_script:
  - python2 --version
  - python3 --version

stages:
  - lint
  - test

lint:unit-simple:
  stage: lint
  script:
    - cd unit-simple
    - pylint --rcfile=../pylintrc unit_simple.py

lint:unit-simple:test:
  stage: lint
  script:
    - cd unit-simple
    - pylint --rcfile=../pylintrc test.py

test:unit-simple:python2:
  stage: test
  script:
    - cd unit-simple
    - python2 test.py

test:unit-simple:python3:
  stage: test
  script:
    - cd unit-simple
    - python3 test.py


