.lint:
  stage: lint
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^$PACKAGE_NAME_/
  script:
    - cd $PACKAGE_NAME
    - conda env create --yes --file environment_lint.yml
    - conda activate lint
    - conda list
    - pip install .

.lint_test:
  stage: lint
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^$PACKAGE_NAME_/
  script:
    - cd $PACKAGE_NAME
    - conda env create --yes --file environment_lint_test.yml
    - conda activate lint_test
    - conda list
    - pip install .
