default:
  before_script:
    - echo $CONDA_HOME
    - PATH=$PATH:$CONDA_HOME/bin
    - . ./init_conda.sh cosmoloj_py 3.11

  after_script:
    - PATH=$PATH:$CONDA_HOME/bin
    - . ./clean_conda.sh cosmoloj_py

stages:
  - envs
  - lint
  - doc
  - test
  - python-version-support
  - coverage
  - demo
  - pypi-package
  - pypi-publish
  - conda-package
  - sonar

include:
  - local: 'simpleunit/.gitlab-ci.yml'
  - local: 'taxref/.gitlab-ci.yml'
  - local: 'coordop/.gitlab-ci.yml'
  - local: 'multienv/.gitlab-ci.yml'
  - local: 'bibliograpy/.gitlab-ci.yml'

conda_envs:
  stage: envs
  before_script:
    - echo $CONDA_HOME
    - PATH=$PATH:$CONDA_HOME/bin
    - . ./init_conda.sh multienv 3.12
    - conda install -c cosmoloj multienv=0.4.1 -y
  script:
    - cd simpleunit
    - pyenvs deps
    - cd ../taxref
    - pyenvs deps
    - cd ../coordop
    - pyenvs deps
    - cd ../multienv
    - pyenvs deps
    - cd ../bibliograpy
    - pyenvs deps
  after_script:
    - PATH=$PATH:$CONDA_HOME/bin
    - . ./clean_conda.sh multienv
  artifacts:
    when: always
    paths:
      - simpleunit/environment_*
      - taxref/environment_*
      - coordop/environment_*
      - multienv/environment_*
      - bibliograpy/environment_*
    expire_in: 2 days

pylintrc_envs:
  stage: envs
  before_script:
    - echo $CONDA_HOME
    - PATH=$PATH:$CONDA_HOME/bin
    - . ./init_conda.sh multienv 3.12
    - conda install -c cosmoloj multienv=0.4.1 -y
  script:
    - pyenvs lint
  after_script:
    - PATH=$PATH:$CONDA_HOME/bin
    - . ./clean_conda.sh multienv
  artifacts:
    when: always
    paths:
      - pylintrc_*
    expire_in: 2 days

coverage:
  stage: coverage
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - conda install coverage
    - coverage xml
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 2 days

sonar:
  stage: sonar
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - $SONAR_SCANNER_HOME/bin/sonar-scanner -Dsonar.login=$SONAR_LOGIN
  artifacts:
    expire_in: 2 days
