.doc:
  stage: doc
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^$PACKAGE_NAME_/
    - if: $CI_COMMIT_TAG =~ /^$PACKAGE_NAME_/
  script:
    - cd $PACKAGE_NAME
    - conda env create --yes --file environment_${JOB_ENV_ID}.yml
    - conda activate ${JOB_ENV_ID}
    - conda list
    - pip install . # to compile the API docstrings with mkdocstrings
    - source ../resources/doc/version.sh $LANG
    - mkdocs build -d site.$LANG -f mkdocs.$LANG.yml
    - zip -r site.$LANG.zip site.$LANG/
    - source ../resources/doc/publish.sh $LANG $PACKAGE_NAME
  environment:
    name: documentation.$PACKAGE_NAME.$LANG
    url: https://cosmoloj.com/doc/$PACKAGE_NAME/$LANG/master
