default:
  before_script:
    - echo $CONDA_HOME
    - PATH=$PATH:$CONDA_HOME/bin
    - python --version
    - conda --version
    - which python
    - conda init bash
    - conda env list
    - conda list cosmoloj_py
    - conda create -n cosmoloj_py python=3.11 -y
    - . ~/.bashrc
    - conda activate cosmoloj_py
    - conda list
    - which python

  after_script:
    - PATH=$PATH:$CONDA_HOME/bin
    - python --version
    - conda --version
    - which python
    - conda init bash
    - . ~/.bashrc
    - conda remove -n cosmoloj_py --all -y

stages:
  - lint
  - test
  - coverage
  - demo
  - pypi-package
  - pypi-publish
  - conda-package
  - sonar

include:
  - local: 'unit-simple/.gitlab-ci.yml'
#  - local: 'taxref/.gitlab-ci.yml'

coverage:
  stage: coverage
  script:
    - coverage xml
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 2 days

sonar:
  stage: sonar
  script:
    - $SONAR_SCANNER_HOME/bin/sonar-scanner -Dsonar.login=$SONAR_LOGIN
  artifacts:
    expire_in: 2 days
