before_script:
  - python2 --version
  - python3 --version

stages:
  - test

build-unit-simple-python2:
  stage: test
  script:
    - cd unit-simple
    - python2 test.py

build-unit-simple-python3:
  stage: test
  script:
    - cd unit-simple
    - python3 test.py
