default:
  before_script:
    - echo $CONDA_HOME
    - PATH=$PATH:$CONDA_HOME/bin
    - python --version
    - conda --version
    - which python
    - conda init bash
    - conda create -n cosmoloj_py python=3.10
    - . ~/.bashrc
    - conda activate cosmoloj_py
    - which python
    - conda install pylint pytest

  after_script:
    - PATH=$PATH:$CONDA_HOME/bin
    - python --version
    - conda --version
    - which python
    - conda init bash
    - . ~/.bashrc
    - conda activate cosmoloj_py
    - which python
    - conda remove pylint pytest

stages:
  - lint
  - test
  - demo

lint:unit-simple:
  stage: lint
  script:
    - cd unit-simple
    - pylint --rcfile=../pylintrc unit_simple.py
    - pylint --rcfile=../pylintrc demo.py

lint:unit-simple:test:
  stage: lint
  script:
    - cd unit-simple
    - pylint --rcfile=../pylintrc test.py
    - pylint --rcfile=../pylintrc unit_simple_test.py

test:unit-simple:pytest:
  stage: test
  script:
    - cd unit-simple
    - pytest

test:unit-simple:testunit:
  stage: test
  script:
    - cd unit-simple
    - python test.py

demo:unit-simple:
  stage: demo
  script:
    - cd unit-simple
    - python demo.py
