before_script:
  - python3 --version

stages:
  - lint
  - test

lint:unit-simple:
  stage: lint
  script:
    - cd unit-simple
    - pylint --rcfile=../pylintrc unit_simple.py
    - pylint --rcfile=../pylintrc demo.py

lint:unit-simple:test:
  stage: lint
  script:
    - cd unit-simple
    - pylint --rcfile=../pylintrc test.py
    - pylint --rcfile=../pylintrc unit_simple_test.py

test:unit-simple:pytest:
  stage: lint
  script:
    - cd unit-simple
    - python3 -m pytest

test:unit-simple:python3:
  stage: test
  script:
    - cd unit-simple
    - python3 test.py


