.lint_base_script: &lint_base_script
    - cd $PACKAGE_NAME
    - conda env create --yes --file environment_${JOB_ENV_ID}.yml
    - conda activate ${JOB_ENV_ID}
    - conda list
    - pip install .

.lint:
  stage: lint
  variables:
    JOB_ENV_ID: lint
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - *lint_base_script

.lint_test:
  stage: lint
  variables:
    JOB_ENV_ID: lint_test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - *lint_base_script
