lint:unit-simple:
  stage: lint
  when: never
  variables:
    PYTHONPATH: .
  script:
    - cd unit-simple
    - conda env create --force --file environment.yml
    # install tool
    - conda install -c conda-forge pylint=3.0.3
    # install deps for pylint to find
    - conda install -y pytest
    - conda list
    - pylint --rcfile=../pylintrc unit_simple.py
    - pylint --rcfile=../pylintrc demo.py
    - pylint --rcfile=../pylintrc test.py
    - pylint --rcfile=../pylintrc unit_simple_test.py

test:unit-simple:
  stage: test
  variables:
    PYTHONPATH: unit-simple
  script:
    - conda env create --force --file unit-simple/environment.yml
    - conda install -y pytest-cov
    - pytest --cov=unit-simple --junitxml=unit-simple/report.xml --cov-append unit-simple
    - python unit-simple/test.py
  artifacts:
    when: always
    paths:
      - .coverage
      - unit-simple/report.xml
    reports:
      junit: unit-simple/report.xml
    expire_in: 2 days

demo:unit-simple:
  stage: demo
  script:
    - cd unit-simple
    - conda env create --force --file environment.yml
    - pip install .
    - python demo.py

pypi-package:unit-simple:test_pypi:
  stage: pypi-package
  variables:
    DIST_DIR: test_pypi_dist
  script:
    - cd unit-simple
    - conda env create --force --file environment.yml
    - rm -rf $DIST_DIR/
    - sed -i "s#version\ =\ .*#version\ =\ \"$UNIT_SIMPLE_VERSION\"#g" pyproject.toml
    - cat pyproject.toml
    - pip install .
    - conda install -c conda-forge -y build
    - python -m build -o $DIST_DIR
    - ls -l $DIST_DIR
    - conda uninstall -y build
  artifacts:
    paths:
      - unit-simple/$DIST_DIR/*

pypi-package:unit-simple:pypi:
  stage: pypi-package
  variables:
    DIST_DIR: dist
  when: manual
  script:
    - cd unit-simple
    - conda env create --force --file environment.yml
    - rm -rf $DIST_DIR/
    - sed -i "s#version\ =\ .*\$#version\ =\ \"$UNIT_SIMPLE_VERSION\"#g" pyproject.toml
    - cat pyproject.toml
    - pip install .
    - conda install -y build
    - python -m build
    - ls -l $DIST_DIR
    - conda uninstall -y build
  artifacts:
    paths:
      - unit-simple/$DIST_DIR/*

pypi-publish:unit-simple:test_pypi:
  stage: pypi-publish
  variables:
    DIST_DIR: test_pypi_dist
  dependencies:
    - pypi-package:unit-simple:test_pypi
  when: manual
  script:
    - cd unit-simple
    - conda env create --force --file environment.yml
    - conda install -y --update-deps twine
    - python -m twine upload --repository testpypi -u $TEST_PYPI_USERNAME -p $TEST_PYPI_PASSWORD $DIST_DIR/*
    - conda uninstall -y twine

pypi-publish:unit-simple:pypi:
  stage: pypi-publish
  dependencies:
    - pypi-package:unit-simple:pypi
  when: manual
  script:
    - cd unit-simple
    - conda env create --force --file environment.yml
    - conda install -y --update-deps twine
    - python -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
    - conda uninstall -y twine

conda-package:unit-simple:
  stage: conda-package
  variables:
    DIST_DIR: conda_dist
    PACKAGE: unit_simple
    VERSION: $UNIT_SIMPLE_VERSION
  when: manual
  script:
    - cd unit-simple
    - conda env create --force --file environment.yml
    - rm -rf $DIST_DIR/
    - conda skeleton pypi --pypi-url $PYPI_URL --output-dir $DIST_DIR $PACKAGE
    - conda build $DIST_DIR/$PACKAGE
    - anaconda logout
    - anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
    - anaconda upload $CONDA_HOME/conda-bld/linux-64/$PACKAGE-$VERSION-py311_0.tar.bz2
    - anaconda logout
  artifacts:
    paths:
      - unit-simple/$DIST_DIR/*
