lint:pylotable:
  stage: lint
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^pylotable_/
  script:
    - cd pylotable
    - conda env create --yes --file environment_lint.yml
    - conda activate lint
    - conda list
    - pip install .
    - pylint --rcfile=../pylintrc_pylotable-src src
    - pylint --rcfile=../pylintrc_strict demo

lint_test:pylotable:
  stage: lint
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^pylotable_/
  script:
    - cd pylotable
    - conda env create --yes --file environment_lint_test.yml
    - conda activate lint_test
    - conda list
    - pip install .
    - pylint --rcfile=../pylintrc_strict test/test_win_coprocessor.py

doc:en:pylotable:
  stage: doc
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^pylotable_/
    - if: $CI_COMMIT_TAG =~ /^pylotable_/
  script:
    - cd pylotable
    - conda env create --yes --file environment_doc.yml
    - conda activate doc
    - conda list
    - pip install . # to compile the API docstrings with mkdocstrings
    - source ../resources/doc/version.sh en
    - mkdocs build -d site.en -f mkdocs.yml
    - zip -r site.en.zip site.en/
    - source ../resources/doc/publish.sh en pylotable
  environment:
    name: documentation.en
    url: https://cosmoloj.com/doc/pylotable/en/master

doc:fr:pylotable:
  stage: doc
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^pylotable_/
    - if: $CI_COMMIT_TAG =~ /^pylotable_/
  script:
    - cd pylotable
    - conda env create --yes --file environment_doc.yml
    - conda activate doc
    - conda list
    - pip install . # to compile the API docstrings with mkdocstrings
    - source ../resources/doc/version.sh fr
    - mkdocs build -d site.fr -f mkdocs.fr.yml
    - zip -r site.fr.zip site.fr/
    - source ../resources/doc/publish.sh fr pylotable
  environment:
    name: documentation.fr
    url: https://cosmoloj.com/doc/pylotable/fr/master

test:pylotable:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^pylotable_/
  script:
    - cd pylotable
    - conda env create --yes --file environment_test.yml
    - conda activate test
    - conda list
    - pip install .
    - cd ..
    - pytest --cov=pylotable --junitxml=pylotable/report.xml --cov-append pylotable
  artifacts:
    when: always
    paths:
      - .coverage
      - pylotable/report.xml
    reports:
      junit: pylotable/report.xml
    expire_in: 2 days

python-version-support:pylotable:
  stage: python-version-support
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^pylotable_/
  variables:
    PYTHONNOUSERSITE: 1 # shortcuts system python libs installed in ~/.local/lib/python3.x/site-packages
  script:
    - cd pylotable
    - . resources/check_py_version.sh 3.13 || exit 1
    - . resources/check_py_version.sh 3.12 || exit 1

demo:pylotable:
  stage: demo
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^pylotable_/
  script:
    - cd pylotable
    - conda env create --yes --file environment_strict.yml
    - conda activate strict
    - conda list
    - pip install .
    - cd demo
    - python group_coprocessor.py
    - python merge_coprocessor.py

pypi-package:pylotable:pypi:
  stage: pypi-package
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^pylotable_/
    - if: $CI_COMMIT_TAG =~ /^pylotable_/
  script:
    - cd pylotable
    - conda env create --yes --file environment_pypi_pkg.yml
    - conda activate pypi_pkg
    - conda list
    - rm -rf dist/
    - if [ $CI_COMMIT_TAG ] ; then VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f 2) ; else VERSION=$CI_COMMIT_BRANCH ; fi
    - if [ $CI_COMMIT_TAG ] ; then sed -i "s#version\ =\ \"0.0.0\"\$#version\ =\ \"$VERSION\"#g" pyproject.toml ; fi
    - if [ $CI_COMMIT_TAG ] ; then sed -i "s#\(\"Homepage\" = .*/\)master\(/pylotable\)#\1$CI_COMMIT_TAG\2#g" pyproject.toml ; fi
    - sed -i "s#\(\"Documentation\" = .*/\)master#\1$VERSION#g" pyproject.toml
    - cat pyproject.toml
    - cp ../LICENSE.md .
    - pip install .
    - python -m build
    - ls -l $DIST_DIR
  artifacts:
    paths:
      - pylotable/dist/*

pypi-publish:pylotable:test_pypi:
  stage: pypi-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^pylotable_/
  script:
    - cd pylotable
    - conda env create --yes --file environment_pypi_publish.yml
    - conda activate pypi_publish
    - conda list
    - python -m twine upload --repository testpypi -u $TEST_PYPI_USERNAME -p $TEST_PYPI_PASSWORD dist/*
  environment:
    name: test pypi pylotable
    url: https://test.pypi.org/project/pylotable/

pypi-publish:pylotable:pypi:
  stage: pypi-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^pylotable_/
  script:
    - cd pylotable
    - conda env create --yes --file environment_pypi_publish.yml
    - conda activate pypi_publish
    - conda list
    - python -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
  environment:
    name: pypi pylotable
    url: https://pypi.org/project/pylotable/

conda-package:pylotable:
  stage: conda-package
  rules:
    - if: $CI_COMMIT_TAG =~ /^pylotable_/
      when: delayed
      start_in: 5 minutes
  variables:
    DIST_DIR: conda_dist
    PACKAGE: pylotable
  script:
    - cd pylotable
    - conda env create --yes --file environment_conda_publish.yml
    - conda activate conda_publish
    - conda list
    - rm -rf $DIST_DIR/
    - mkdir $DIST_DIR
    - grayskull pypi -o $DIST_DIR $PACKAGE
    - cat $DIST_DIR/$PACKAGE/meta.yaml
    - conda build --numpy=2.0 $DIST_DIR/$PACKAGE
  artifacts:
    paths:
      - pylotable/$DIST_DIR/*

conda-publish:pylotable:
  stage: conda-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^pylotable_/
  variables:
    PACKAGE: pylotable
  script:
    - cd pylotable
    - conda env create --yes --file environment_conda_publish.yml
    - conda activate conda_publish
    - conda list
    - VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f 2)
    - anaconda logout
    - anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
    - anaconda upload $CONDA_HOME/conda-bld/noarch/$PACKAGE-$VERSION-py_0.tar.bz2
    - anaconda logout
  environment:
    name: anaconda pylotable
    url: https://anaconda.org/cosmoloj/pylotable/
