conda_env:pylotable:
  extends: .conda_env
  variables:
    PACKAGE_NAME: pylotable

lint:pylotable:
  extends: .lint
  variables:
    PACKAGE_NAME: pylotable
  script:
    - !reference [.lint, script]
    - pylint --rcfile=../pylintrc_pylotable-src src
    - pylint --rcfile=../pylintrc_strict demo

lint_test:pylotable:
  extends: .lint_test
  variables:
    PACKAGE_NAME: pylotable
  script:
    - !reference [.lint_test, script]
    - pylint --rcfile=../pylintrc_strict test/test_win_coprocessor.py

.pylotable:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^pylotable_/
    - if: $CI_COMMIT_TAG =~ /^pylotable_/

doc:en:pylotable:
  extends: .doc
  variables:
    PACKAGE_NAME: pylotable
    LANG: en
  rules:
    - !reference [.doc, rules]
    - !reference [.pylotable, rules]

doc:fr:pylotable:
  extends: .doc
  variables:
    PACKAGE_NAME: pylotable
    LANG: fr
  rules:
    - !reference [.doc, rules]
    - !reference [.pylotable, rules]

test:pylotable:
  extends: .test
  variables:
    PACKAGE_NAME: pylotable

python-version-support:pylotable:
  extends: .python-version-support
  variables:
    PACKAGE_NAME: pylotable
  script:
    - !reference [.python-version-support, script]
    - . resources/check_py_version.sh 3.13 || exit 1
    - . resources/check_py_version.sh 3.12 || exit 1

demo:pylotable:
  extends: .demo
  variables:
    PACKAGE_NAME: pylotable
  script:
    - !reference [.demo, script]
    - python group_coprocessor.py
    - python merge_coprocessor.py

pypi-package:pylotable:
  extends: .pypi-package
  variables:
    PACKAGE_NAME: pylotable

pypi-publish-test:pylotable:
  extends: .pypi-publish-test
  variables:
    PACKAGE_NAME: pylotable

pypi-publish:pylotable:
  extends: .pypi-publish
  variables:
    PACKAGE_NAME: pylotable

conda-package:pylotable:
  stage: conda-package
  rules:
    - if: $CI_COMMIT_TAG =~ /^pylotable_/
      when: delayed
      start_in: 5 minutes
  variables:
    DIST_DIR: conda_dist
    PACKAGE: pylotable
  script:
    - cd pylotable
    - conda env create --yes --file environment_conda_publish.yml
    - conda activate conda_publish
    - conda list
    - rm -rf $DIST_DIR/
    - mkdir $DIST_DIR
    - grayskull pypi -o $DIST_DIR $PACKAGE
    - cat $DIST_DIR/$PACKAGE/meta.yaml
    - conda build --numpy=2.0 $DIST_DIR/$PACKAGE
  artifacts:
    paths:
      - pylotable/$DIST_DIR/*

conda-publish:pylotable:
  stage: conda-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^pylotable_/
  variables:
    PACKAGE: pylotable
  script:
    - cd pylotable
    - conda env create --yes --file environment_conda_publish.yml
    - conda activate conda_publish
    - conda list
    - VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f 2)
    - anaconda logout
    - anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
    - anaconda upload $CONDA_HOME/conda-bld/noarch/$PACKAGE-$VERSION-py_0.tar.bz2
    - anaconda logout
  environment:
    name: anaconda pylotable
    url: https://anaconda.org/cosmoloj/pylotable/
