conda_env:multienv:
  extends: .conda_env
  variables:
    PACKAGE_NAME: multienv

lint:multienv:
  extends: .lint
  variables:
    PACKAGE_NAME: multienv
  script:
    - !reference [.lint, script]
    - pylint --rcfile=../pylintrc_multienv-src src

lint_test:multienv:
  extends: .lint_test
  variables:
    PACKAGE_NAME: multienv
  script:
    - !reference [.lint_test, script]
    - pylint --rcfile=../pylintrc_src test/test_pyenvs.py
    - pylint --rcfile=../pylintrc_src test/test_pyenvs_info.py
    - pylint --rcfile=../pylintrc_src test/test_pyenvs_deps.py
    - pylint --rcfile=../pylintrc_src test/test_pyenvs_deps_formatter.py
    - pylint --rcfile=../pylintrc_src test/test_pyenvs_deps_input_std.py
    - pylint --rcfile=../pylintrc_test test/test_pyenvs_deps_output_conda.py
    - pylint --rcfile=../pylintrc_src test/test_pyenvs_deps_output_pip.py
    - pylint --rcfile=../pylintrc_src test/test_pyenvs_lint.py
    - pylint --rcfile=../pylintrc_src test/test_pyenvs_lint_input_std.py
    - pylint --rcfile=../pylintrc_src test/test_pyenvs_lint_formatter.py
    - pylint --rcfile=../pylintrc_test test/test_pyenvs_lint_output_pylint.py

doc:en:multienv:
  extends: .doc
  variables:
    PACKAGE_NAME: multienv
    LANG: en
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^multienv_/
    - if: $CI_COMMIT_TAG =~ /^multienv_/

test:multienv:
  extends: .test
  variables:
    PACKAGE_NAME: multienv

python-version-support:multienv:
  extends: .python-version-support
  variables:
    PACKAGE_NAME: multienv
  script:
    - !reference [.python-version-support, script]
    - . resources/check_py_version.sh 312

demo:multienv:
  extends: .demo
  variables:
    PACKAGE_NAME: multienv
  script:
    - !reference [.demo, script]
    - . demo.sh

pypi-package:multienv:
  extends: .pypi-package
  variables:
    PACKAGE_NAME: multienv

pypi-publish-test:multienv:
  extends: .pypi-publish-test
  variables:
    PACKAGE_NAME: multienv

pypi-publish:multienv:
  extends: .pypi-publish
  variables:
    PACKAGE_NAME: multienv

conda-package:multienv:
  stage: conda-package
  rules:
    - if: $CI_COMMIT_TAG =~ /^multienv_/
      when: delayed
      start_in: 5 minutes
  variables:
    DIST_DIR: conda_dist
    PACKAGE: multienv
  script:
    - cd multienv
    - conda env create --yes --file environment_conda_publish.yml
    - conda activate conda_publish
    - conda list
    - rm -rf $DIST_DIR/
    - mkdir $DIST_DIR
    - grayskull pypi -o $DIST_DIR $PACKAGE
    - cat $DIST_DIR/$PACKAGE/meta.yaml
    - conda build --numpy=2.0 $DIST_DIR/$PACKAGE
  artifacts:
    paths:
      - multienv/$DIST_DIR/*

conda-publish:multienv:
  stage: conda-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^multienv_/
  variables:
    PACKAGE: multienv
  script:
    - cd multienv
    - conda env create --yes --file environment_conda_publish.yml
    - conda activate conda_publish
    - conda list
    - VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f 2)
    - anaconda logout
    - anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
    - anaconda upload $CONDA_HOME/conda-bld/noarch/$PACKAGE-$VERSION-py_0.tar.bz2
    - anaconda logout
  environment:
    name: anaconda multienv
    url: https://anaconda.org/cosmoloj/multienv/
