lint:multienv:
  stage: lint
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - cd simpleunit
    - conda env create --yes --file environment.yml
    # install tool
    - conda install -y pylint
    - conda list
    - pip install .
    - pylint --rcfile=../pylintrc src
    # install deps for pylint to find
    - conda install -y pytest
    - pylint --rcfile=../pylintrc test/test_pyenvs.py

test:multienv:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - cd multienv
    - conda env create --yes --file environment.yml
    - conda install -y pytest-cov
    - pip install .
    - cd ..
    - pytest --cov=multienv --junitxml=multienv/report.xml --cov-append multienv
  artifacts:
    when: always
    paths:
      - .coverage
      - multienv/report.xml
    reports:
      junit: multienv/report.xml
    expire_in: 2 days

python-version-support:multienv:
  stage: python-version-support
  rules:
    - if: $CI_COMMIT_TAG == null
  variables:
    PYTHONNOUSERSITE: 1 # shortcuts system python libs installed in ~/.local/lib/python3.x/site-packages
  script:
    - cd multienv
    - . resources/check_py_version.sh 3.11 || exit 1
    - . resources/check_py_version.sh 3.12 || exit 1

pypi-package:multienv:pypi:
  stage: pypi-package
  rules:
    - if: $CI_COMMIT_TAG =~ /^multienv_/ || $CI_COMMIT_TAG == null
  script:
    - cd multienv
    - conda env create --yes --file environment.yml
    - rm -rf dist/
    - if [ $CI_COMMIT_TAG ] ; then VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f 2) ; else VERSION=$CI_COMMIT_BRANCH ; fi
    - if [ $CI_COMMIT_TAG ] ; then sed -i "s#version\ =\ \"0.0.0\"\$#version\ =\ \"$VERSION\"#g" pyproject.toml ; fi
    - if [ $CI_COMMIT_TAG ] ; then sed -i "s#\(\"Homepage\" = .*/\)master\(/multienv\)#\1$CI_COMMIT_TAG\2#g" pyproject.toml ; fi
    - sed -i "s#\(\"Documentation\" = .*/\)master#\1$VERSION#g" pyproject.toml
    - cat pyproject.toml
    - cp ../LICENSE.md .
    - pip install .
    - pip install build
    - python -m build
    - ls -l $DIST_DIR
    - pip uninstall -y build
  artifacts:
    paths:
      - multienv/dist/*

pypi-publish:multienv:test_pypi:
  stage: pypi-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^multienv_/
      when: manual
    - when: never
  dependencies:
    - pypi-package:multienv:pypi
  script:
    - cd multienv
    - conda env create --yes --file environment.yml
    - conda install -y --update-deps twine
    - python -m twine upload --repository testpypi -u $TEST_PYPI_USERNAME -p $TEST_PYPI_PASSWORD dist/*
    - conda uninstall -y twine
  environment:
    name: test pypi multienv
    url: https://test.pypi.org/project/multienv/

pypi-publish:multienv:pypi:
  stage: pypi-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^multienv_/
      when: manual
    - when: never
  dependencies:
    - pypi-package:multienv:pypi
  script:
    - cd multienv
    - conda env create --yes --file environment.yml
    - conda install -y --update-deps twine
    - python -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
    - conda uninstall -y twine
  environment:
    name: pypi multienv
    url: https://pypi.org/project/multienv/

conda-package:multienv:
  stage: conda-package
  rules:
    - if: $CI_COMMIT_TAG =~ /^multienv_/
      when: manual
    - when: never
  variables:
    DIST_DIR: conda_dist
    PACKAGE: multienv
  script:
    - cd multienv
    - conda env create --yes --file environment.yml
    - VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f 2)
    - rm -rf $DIST_DIR/
    - mkdir $DIST_DIR
    - conda install -c conda-forge grayskull
    - grayskull pypi -o $DIST_DIR $PACKAGE
    - cat $DIST_DIR/$PACKAGE/meta.yaml
    - conda build $DIST_DIR/$PACKAGE
    - anaconda logout
    - anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
    - anaconda upload $CONDA_HOME/conda-bld/noarch/$PACKAGE-$VERSION-py_0.tar.bz2
    - anaconda logout
  artifacts:
    paths:
      - multienv/$DIST_DIR/*
  environment:
    name: anaconda multienv
    url: https://anaconda.org/cosmoloj/multienv/
