lint:unit_simple:
  stage: lint
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - cd unit_simple
    - conda env create --force --file environment.yml
    # install tool
    - conda install -y pylint
    - conda list
    - pip install .
    - pylint --rcfile=../pylintrc src
    - pylint --rcfile=../pylintrc demo.py
    # install deps for pylint to find
    - conda install -y pytest
    - pylint --rcfile=../pylintrc test/test.py
    - pylint --rcfile=../pylintrc test/unit_simple_test.py
    - pylint --rcfile=../pylintrc test/unit_simple_operator_test.py
    - pylint --rcfile=../pylintrc test/unit_simple_built_in_test.py

mkdocs:unit_simple:
  stage: doc
  rules:
    - if: $CI_COMMIT_TAG =~ /^unit-simple_/ || $CI_COMMIT_TAG == null
  script:
    - cd unit_simple
    - conda install -c conda-forge mkdocs=1.6 mkdocstrings mkdocstrings-python -y
    - pip install . # to compile the API docstrings with mkdocstrings
    - if [ $CI_COMMIT_TAG ] ; then VERSION=$(echo $CI_COMMIT_TAG | cut -d'-' -f 2) ; else VERSION=$CI_COMMIT_BRANCH ; fi
    - echo $'\n**Version '$VERSION'**' >> docs/about.md
    - echo $'\nDocumentation generated at '$(date -u +"%F %T")' UTC' >> docs/about.md
    - mkdocs build
    - zip -r site.zip site/
    - ssh $PUBLIC_SITE_USER@$PUBLIC_SITE_SERVER "mkdir -p $PUBLIC_SITE_SERVER_PATH/mkdocs/unit-simple"
    - scp site.zip $PUBLIC_SITE_USER@$PUBLIC_SITE_SERVER:$PUBLIC_SITE_SERVER_PATH/mkdocs/unit-simple
    - ssh $PUBLIC_SITE_USER@$PUBLIC_SITE_SERVER "cd $PUBLIC_SITE_SERVER_PATH/mkdocs/unit-simple ; rm -rf $VERSION ; unzip site.zip ; mv site $VERSION ; rm site.zip"
    - if [ $CI_COMMIT_TAG ] ; then ssh $PUBLIC_SITE_USER@$PUBLIC_SITE_SERVER "cd $PUBLIC_SITE_SERVER_PATH/mkdocs/unit-simple ; rm latest ; ln -s $VERSION latest" ; fi
  environment:
    name: documentation
    url: https://cosmoloj.com/mkdocs/unit-simple/master

test:unit_simple:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - cd unit_simple
    - conda env create --force --file environment.yml
    - conda install -y pytest-cov
    - pip install .
    - cd ..
    - pytest --cov=unit_simple --junitxml=unit_simple/report.xml --cov-append unit_simple
    - python unit_simple/test/test.py
  artifacts:
    when: always
    paths:
      - .coverage
      - unit_simple/report.xml
    reports:
      junit: unit_simple/report.xml
    expire_in: 2 days

python-version-support:unit_simple:
  stage: python-version-support
  rules:
    - if: $CI_COMMIT_TAG == null
  variables:
    PYTHONNOUSERSITE: 1 # shortcuts system python libs installed in ~/.local/lib/python3.x/site-packages
  script:
    - cd unit_simple
    - . resources/check_py_support.sh

demo:unit_simple:
  stage: demo
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - cd unit_simple
    - conda env create --force --file environment.yml
    - pip install .
    - python demo.py

pypi-package:unit_simple:pypi:
  stage: pypi-package
  rules:
    - if: $CI_COMMIT_TAG =~ /^unit-simple_/ || $CI_COMMIT_TAG == null
  script:
    - cd unit_simple
    - conda env create --force --file environment.yml
    - rm -rf dist/
    - if [ $CI_COMMIT_TAG ] ; then VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f 2) ; else VERSION=$CI_COMMIT_BRANCH ; fi
    - if [ $CI_COMMIT_TAG ] ; then sed -i "s#version\ =\ \"0.0.0\"\$#version\ =\ \"$VERSION\"#g" pyproject.toml ; fi
    - if [ $CI_COMMIT_TAG ] ; then sed -i "s#\(\"Homepage\" = .*/\)master\(/unit-simple\)#\1$CI_COMMIT_TAG\2#g" pyproject.toml ; fi
    - sed -i "s#\(\"Documentation\" = .*/\)master#\1$VERSION#g" pyproject.toml
    - cat pyproject.toml
    - cp ../LICENSE.md .
    - pip install .
    - conda install -y build
    - python -m build
    - ls -l $DIST_DIR
    - conda uninstall -y build
  artifacts:
    paths:
      - unit_simple/dist/*

pypi-publish:unit_simple:test_pypi:
  stage: pypi-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^unit-simple_/
    - when: never
  dependencies:
    - pypi-package:unit_simple:pypi
  script:
    - cd unit_simple
    - conda env create --force --file environment.yml
    - conda install -y --update-deps twine
    - python -m twine upload --repository testpypi -u $TEST_PYPI_USERNAME -p $TEST_PYPI_PASSWORD dist/*
    - conda uninstall -y twine
  environment:
    name: test pypi simple unit
    url: https://test.pypi.org/project/unit-simple/

pypi-publish:unit_simple:pypi:
  stage: pypi-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^unit-simple_/
    - when: never
  dependencies:
    - pypi-package:unit_simple:pypi
  script:
    - cd unit_simple
    - conda env create --force --file environment.yml
    - conda install -y --update-deps twine
    - python -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
    - conda uninstall -y twine
  environment:
    name: pypi simple unit
    url: https://pypi.org/project/unit-simple/

conda-package:unit_simple:
  stage: conda-package
  rules:
    - if: $CI_COMMIT_TAG =~ /^unit-simple_/
      when: manual
    - when: never
  variables:
    DIST_DIR: conda_dist
    PACKAGE: unit-simple
  script:
    - cd unit_simple
    - conda env create --force --file environment.yml
    - VERSION=$(echo $CI_COMMIT_TAG | cut -d'-' -f 2)
    - rm -rf $DIST_DIR/
    - mkdir $DIST_DIR
    - conda install -c conda-forge grayskull
    - grayskull pypi -o $DIST_DIR "$PACKAGE"
    - cat $DIST_DIR/$PACKAGE/meta.yaml
    - conda build $DIST_DIR/$PACKAGE
    - anaconda logout
    - anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
    - anaconda upload $CONDA_HOME/conda-bld/noarch/$PACKAGE_$VERSION-py_0.tar.bz2
    - anaconda logout
  artifacts:
    paths:
      - unit_simple/$DIST_DIR/*
  environment:
    name: anaconda simple unit
    url: https://anaconda.org/cosmoloj/unit-simple/
