site_name: Simple Unit (Python RI)
nav:
  - Specification: specification.md
  - Standard: standard.md
  - Operators: operators.md
  - API: api.md
theme: mkdocs  # readthedocs
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - admonition
