conda_env:coordop:
  extends: .conda_env
  variables:
    PACKAGE_NAME: coordop

lint:coordop:
  extends: .lint
  variables:
    PACKAGE_NAME: coordop
  script:
    - !reference [.lint, script]
    - bibliograpy process --output-dir src/coordop -s SHARED_SCOPE bibliograpy.bib
    - pylint --rcfile=../pylintrc_coordop-src --ignore-paths src/coordop/bibliography.py src

lint_test:coordop:
  extends: .lint_test
  variables:
    PACKAGE_NAME: coordop
  script:
    - !reference [.lint_test, script]
    - bibliograpy process --output-dir src/coordop -s SHARED_SCOPE bibliograpy.bib
    - pylint --rcfile=../pylintrc_test test/projection/*

doc:en:coordop:
  extends: .doc
  variables:
    PACKAGE_NAME: coordop
    LANG: en

test:coordop:
  extends: .test
  variables:
    PACKAGE_NAME: coordop
  script:
    - cd coordop
    - conda env create --yes --file environment_test.yml
    - conda activate test
    - conda list
    - pip install .
    - bibliograpy process --output-dir src/coordop -s SHARED_SCOPE bibliograpy.bib
    - pip install .
    - cd ..
    - pytest --cov=coordop --junitxml=coordop/report.xml --cov-append coordop

python-version-support:coordop:
  extends: .python-version-support
  variables:
    PACKAGE_NAME: coordop
  script:
    - !reference [.python-version-support, script]
    - . resources/check_py_version.sh 3.13 || exit 1
    - . resources/check_py_version.sh 3.12 || exit 1

pypi-package:coordop:pypi:
  stage: pypi-package
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^coordop_/
    - if: $CI_COMMIT_TAG =~ /^coordop_/
  script:
    - cd coordop
    - conda env create --yes  --file environment_pypi_pkg.yml
    - conda activate pypi_pkg
    - conda list
    - rm -rf dist/
    - if [ $CI_COMMIT_TAG ] ; then VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f 2) ; else VERSION=$CI_COMMIT_BRANCH ; fi
    - if [ $CI_COMMIT_TAG ] ; then sed -i "s#version\ =\ \"0.0.0\"\$#version\ =\ \"$VERSION\"#g" pyproject.toml ; fi
    - if [ $CI_COMMIT_TAG ] ; then sed -i "s#\(\"Homepage\" = .*/\)master\(/coordop\)#\1$CI_COMMIT_TAG\2#g" pyproject.toml ; fi
    - sed -i "s#\(\"Documentation\" = .*/\)master#\1$VERSION#g" pyproject.toml
    - cat pyproject.toml
    - cp ../LICENSE.md .
    - pip install .
    - bibliograpy process --output-dir src/coordop -s SHARED_SCOPE bibliograpy.bib
    - pip install .
    - python -m build
    - ls -l $DIST_DIR
  artifacts:
    paths:
      - coordop/dist/*

pypi-publish:coordop:test_pypi:
  stage: pypi-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^coordop_/
  script:
    - cd coordop
    - conda env create --yes --file environment_pypi_publish.yml
    - conda activate pypi_publish
    - conda list
    - python -m twine upload --repository testpypi -u $TEST_PYPI_USERNAME -p $TEST_PYPI_PASSWORD dist/*
  environment:
    name: test pypi math operation
    url: https://test.pypi.org/project/coordop/

pypi-publish:coordop:pypi:
  stage: pypi-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^coordop_/
  script:
    - cd coordop
    - conda env create --yes --file environment_pypi_publish.yml
    - conda activate pypi_publish
    - conda list
    - python -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
  environment:
    name: pypi math operation
    url: https://pypi.org/project/coordop/

conda-package:coordop:
  stage: conda-package
  rules:
    - if: $CI_COMMIT_TAG =~ /^coordop_/
      when: delayed
      start_in: 5 minutes
  variables:
    DIST_DIR: conda_dist
    PACKAGE: coordop
  script:
    - cd coordop
    - conda env create --yes --file environment_conda_publish.yml
    - conda activate conda_publish
    - conda list
    - rm -rf $DIST_DIR/
    - mkdir $DIST_DIR
    - grayskull pypi -o $DIST_DIR $PACKAGE
    - cat $DIST_DIR/$PACKAGE/meta.yaml
    - conda build --numpy=2.0 -c conda-forge $DIST_DIR/$PACKAGE
  artifacts:
    paths:
      - coordop/$DIST_DIR/*

conda-publish:coordop:
  stage: conda-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^coordop_/
  variables:
    PACKAGE: coordop
  script:
    - cd coordop
    - conda env create --yes --file environment_conda_publish.yml
    - conda activate conda_publish
    - conda list
    - VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f 2)
    - anaconda logout
    - anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
    - anaconda upload $CONDA_HOME/conda-bld/noarch/$PACKAGE-$VERSION-py_0.tar.bz2
    - anaconda logout
  environment:
    name: anaconda math operation
    url: https://anaconda.org/cosmoloj/coordop/
