conda_env:simple_unit:
  extends: .conda_env
  variables:
    PACKAGE_NAME: simpleunit

lint:simpleunit:
  extends: .lint
  variables:
    PACKAGE_NAME: simpleunit
  script:
    - !reference [.lint, script]
    - pylint --rcfile=../pylintrc_src src
    - pylint --rcfile=../pylintrc_src demo/demo.py

lint_test:simpleunit:
  extends: .lint_test
  variables:
    PACKAGE_NAME: simpleunit
  script:
    - !reference [.lint_test, script]
    - pylint --rcfile=../pylintrc_src test/test.py
    - pylint --rcfile=../pylintrc_src test/unit_simple_test.py
    - pylint --rcfile=../pylintrc_src test/unit_simple_operator_test.py
    - pylint --rcfile=../pylintrc_src test/unit_simple_built_in_test.py

doc:en:simpleunit:
  extends: .doc
  variables:
    PACKAGE_NAME: pylotable
    LANG: en

test:simpleunit:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^simpleunit_/
  script:
    - cd simpleunit
    - conda env create --yes --file environment_test.yml
    - conda activate test
    - conda list
    - pip install .
    - cd ..
    - pytest --cov=simpleunit --junitxml=simpleunit/report.xml --cov-append simpleunit
    - python simpleunit/test/test.py
  artifacts:
    when: always
    paths:
      - .coverage
      - simpleunit/report.xml
    reports:
      junit: simpleunit/report.xml
    expire_in: 2 days

python-version-support:simpleunit:
  stage: python-version-support
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^simpleunit_/
  variables:
    PYTHONNOUSERSITE: 1 # shortcuts system python libs installed in ~/.local/lib/python3.x/site-packages
  script:
    - cd simpleunit
    - . resources/check_py_version.sh 3.14 || exit 1
    - . resources/check_py_version.sh 3.13 || exit 1

demo:simpleunit:
  stage: demo
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^simpleunit_/
  script:
    - cd simpleunit
    - conda env create --yes --file environment_strict.yml
    - conda activate strict
    - conda list
    - pip install .
    - cd demo
    - python demo.py

pypi-package:simpleunit:pypi:
  stage: pypi-package
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^simpleunit_/
    - if: $CI_COMMIT_TAG =~ /^simpleunit_/
  script:
    - cd simpleunit
    - conda env create --yes --file environment_pypi_pkg.yml
    - conda activate pypi_pkg
    - conda list
    - rm -rf dist/
    - if [ $CI_COMMIT_TAG ] ; then VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f 2) ; else VERSION=$CI_COMMIT_BRANCH ; fi
    - if [ $CI_COMMIT_TAG ] ; then sed -i "s#version\ =\ \"0.0.0\"\$#version\ =\ \"$VERSION\"#g" pyproject.toml ; fi
    - if [ $CI_COMMIT_TAG ] ; then sed -i "s#\(\"Homepage\" = .*/\)master\(/simpleunit\)#\1$CI_COMMIT_TAG\2#g" pyproject.toml ; fi
    - sed -i "s#\(\"Documentation\" = .*/\)master#\1$VERSION#g" pyproject.toml
    - cat pyproject.toml
    - cp ../LICENSE.md .
    - pip install .
    - python -m build
    - ls -l $DIST_DIR
  artifacts:
    paths:
      - simpleunit/dist/*

pypi-publish:simpleunit:test_pypi:
  stage: pypi-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^simpleunit_/
  script:
    - cd simpleunit
    - conda env create --yes --file environment_pypi_publish.yml
    - conda activate pypi_publish
    - conda list
    - python -m twine upload --repository testpypi -u $TEST_PYPI_USERNAME -p $TEST_PYPI_PASSWORD dist/*
  environment:
    name: test pypi simpleunit
    url: https://test.pypi.org/project/simpleunit/

pypi-publish:simpleunit:pypi:
  stage: pypi-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^simpleunit_/
  script:
    - cd simpleunit
    - conda env create --yes --file environment_pypi_publish.yml
    - conda activate pypi_publish
    - conda list
    - python -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
  environment:
    name: pypi simpleunit
    url: https://pypi.org/project/simpleunit/

conda-package:simpleunit:
  stage: conda-package
  rules:
    - if: $CI_COMMIT_TAG =~ /^simpleunit_/
      when: delayed
      start_in: 5 minutes
  variables:
    DIST_DIR: conda_dist
    PACKAGE: simpleunit
  script:
    - cd simpleunit
    - conda env create --yes --file environment_conda_publish.yml
    - conda activate conda_publish
    - conda list
    - rm -rf $DIST_DIR/
    - mkdir $DIST_DIR
    - grayskull pypi -o $DIST_DIR $PACKAGE
    - cat $DIST_DIR/$PACKAGE/meta.yaml
    - conda build --numpy=2.0 $DIST_DIR/$PACKAGE
  artifacts:
    paths:
      - simpleunit/$DIST_DIR/*

conda-publish:simpleunit:
  stage: conda-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^simpleunit_/
  variables:
    PACKAGE: simpleunit
  script:
    - cd simpleunit
    - conda env create --yes --file environment_conda_publish.yml
    - conda activate conda_publish
    - conda list
    - VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f 2)
    - anaconda logout
    - anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
    - anaconda upload $CONDA_HOME/conda-bld/noarch/$PACKAGE-$VERSION-py_0.tar.bz2
    - anaconda logout
  environment:
    name: anaconda simpleunit
    url: https://anaconda.org/cosmoloj/simpleunit/
