conda_env:simpleunit:
  extends: .conda_env
  variables:
    PACKAGE_NAME: simpleunit

lint:simpleunit:
  extends: .lint
  variables:
    PACKAGE_NAME: simpleunit
  script:
    - !reference [.lint, script]
    - pylint --rcfile=../pylintrc_src src
    - pylint --rcfile=../pylintrc_src demo/demo.py

lint_test:simpleunit:
  extends: .lint_test
  variables:
    PACKAGE_NAME: simpleunit
  script:
    - !reference [.lint_test, script]
    - pylint --rcfile=../pylintrc_src test/test.py
    - pylint --rcfile=../pylintrc_src test/unit_simple_test.py
    - pylint --rcfile=../pylintrc_src test/unit_simple_operator_test.py
    - pylint --rcfile=../pylintrc_src test/unit_simple_built_in_test.py

doc:en:simpleunit:
  extends: .doc
  variables:
    PACKAGE_NAME: simpleunit
    LANG: en
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^simpleunit_/
    - if: $CI_COMMIT_TAG =~ /^simpleunit_/

test:simpleunit:
  extends: .test
  variables:
    PACKAGE_NAME: simpleunit
  script:
    - !reference [.test, script]
    - python simpleunit/test/test.py

python-version-support:simpleunit:
  extends: .python-version-support
  variables:
    PACKAGE_NAME: simpleunit
  script:
    - !reference [.python-version-support, script]
    - . resources/check_py_version.sh 3.14 || exit 1
    - . resources/check_py_version.sh 3.13 || exit 1

demo:simpleunit:
  extends: .demo
  variables:
    PACKAGE_NAME: simpleunit
  script:
    - !reference [.demo, script]
    - python demo.py

pypi-package:simpleunit:
  extends: .pypi-package
  variables:
    PACKAGE_NAME: simpleunit

pypi-publish-test:simpleunit:
  extends: .pypi-publish-test
  variables:
    PACKAGE_NAME: simpleunit

pypi-publish:simpleunit:
  extends: .pypi-publish
  variables:
    PACKAGE_NAME: simpleunit

conda-package:simpleunit:
  stage: conda-package
  rules:
    - if: $CI_COMMIT_TAG =~ /^simpleunit_/
      when: delayed
      start_in: 5 minutes
  variables:
    DIST_DIR: conda_dist
    PACKAGE: simpleunit
  script:
    - cd simpleunit
    - conda env create --yes --file environment_conda_publish.yml
    - conda activate conda_publish
    - conda list
    - rm -rf $DIST_DIR/
    - mkdir $DIST_DIR
    - grayskull pypi -o $DIST_DIR $PACKAGE
    - cat $DIST_DIR/$PACKAGE/meta.yaml
    - conda build --numpy=2.0 $DIST_DIR/$PACKAGE
  artifacts:
    paths:
      - simpleunit/$DIST_DIR/*

conda-publish:simpleunit:
  stage: conda-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^simpleunit_/
  variables:
    PACKAGE: simpleunit
  script:
    - cd simpleunit
    - conda env create --yes --file environment_conda_publish.yml
    - conda activate conda_publish
    - conda list
    - VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f 2)
    - anaconda logout
    - anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
    - anaconda upload $CONDA_HOME/conda-bld/noarch/$PACKAGE-$VERSION-py_0.tar.bz2
    - anaconda logout
  environment:
    name: anaconda simpleunit
    url: https://anaconda.org/cosmoloj/simpleunit/
