from bibliograpy.api_mesh import *
from bibliograpy.api_pubmed import *


PUBMED_16596158 = {
  Tags.PMID: '16596158',
  Tags.OWN: 'NLM',
  Tags.STAT: 'MEDLINE',
  Tags.DCOM: '20060619',
  Tags.LR: '20151119',
  Tags.IS: '0048-0169 (Linking)',
  Tags.VI: '54',
  Tags.IP: '2',
  Tags.DP: '2006 Apr',
  Tags.TI: 'Comparison of a camera - software system and typical farm management for       detecting oestrus in dairy cattle at pasture.',
  Tags.PG: '73-7',
  Tags.AB: 'AIM: To compare the sensitivity, specificity, predictive values and accuracy of       detection of oestrus using a novel oestrus detection strip (ODS) and a       camera-software device (CSD) with typical farm management practices of visual       observation and use of tail paint in dairy cattle at pasture. METHODS: Dairy cows       (n = 480) in a seasonal-calving herd managed at pasture under typical commercial       conditions in New Zealand were stratified by age, body condition score and days       in milk, then randomly allocated to one of two groups prior to the planned start       of mating (PSM). Tail paint was applied to all cows and oestrus detected by       visual observation of oestrous behaviour and removal of paint, by farm staff. One       group (n = 240) was fitted with ODS and also monitored for signs of oestrus using       a CSD, while the Control group (n = 240) was monitored using tail paint and       visual observations only. Cows detected in oestrus were artificially inseminated       (AI), and pregnancy status determined using rectal palpation and ultrasonography,       51-52 days after the end of a 55-day A period. Results of pregnancy diagnosis       were used to confirm the occurrence of oestrus, and the sensitivity, specificity,       predictive value and accuracy of detection of oestrus compared between oestrus       detection methods. RESULTS: The sensitivity and accuracy of oestrus detection in       the Control group, using visual observation and tail paint, were low. Compared       with the Control group, detection of oestrus using the ODS and CSD resulted in       greater sensitivity (85% vs 78%; p = 0.006), specificity (99.6% vs 98.0%; p <       0.001), positive predictive value (PPV; 88% vs 51%; p < 0.001) and overall       accuracy (99.0% vs 98.0%; p < 0.001). Negative predictive value (NPV) did not       differ significantly between groups (99.4% vs 99.3%; p = 0.28). Pregnancy rate to       first service was higher in the CSD group than in the Control group (72% vs 39%;       p < 0.05). Use of the CSD significantly increased the cumulative proportion of       cows pregnant to AI over the breeding period (p = 0.044). CONCLUSION AND CLINICAL       RELEVANCE: The ODS and CSD was satisfactory for detection of oestrus in seasonal       calving dairy herds grazing on pasture and could improve the sensitivity and       accuracy of detection of oestrus in herds where these are low.',
  Tags.FAU: 'Bailey, D',
  Tags.AU: ['Alawneh JI', 'Williamson NB', 'Bailey D'],
  Tags.AD: 'Institute of Veterinary, Animal and Biomedical Sciences, Massey University,       Private Bag 11222, Palmerston North, New Zealand. ibr_ala@yahoo.co.nz',
  Tags.LA: 'eng',
  Tags.PT: [MeshPublicationType.COMPARATIVE_STUDY, MeshPublicationType.JOURNAL_ARTICLE, ],
  Tags.PL: 'England',
  Tags.TA: 'N Z Vet J',
  Tags.JT: 'New Zealand veterinary journal',
  Tags.JID: '0021406',
  Tags.RN: ['0 (Reagent Strips)'],
  Tags.SB: 'IM',
  Tags.MH: ['Animals', 'Cattle/*physiology', 'Dairying', 'Estrus Detection/*methods/*standards', 'Female', 'Insemination, Artificial/veterinary', 'Predictive Value of Tests', 'Pregnancy', 'Pregnancy Rate', 'Reagent Strips', 'Reproducibility of Results', 'Sensitivity and Specificity', 'Software'],
  Tags.EDAT: '2006/04/06 09:00',
  Tags.MHDA: '2006/06/20 09:00',
  Tags.CRDT: '2006/04/06 09:00',
  Tags.PHST: '2006/04/06 09:00 [entrez]',
  Tags.AID: '10.1080/00480169.2006.36615 [doi]',
  Tags.PST: 'ppublish',
  Tags.SO: 'N Z Vet J. 2006 Apr;54(2):73-7. doi: 10.1080/00480169.2006.36615.',
}
BIS_16596158 = {
  Tags.PMID: 'bis_16596158',
  Tags.OWN: 'NLM',
  Tags.STAT: 'MEDLINE',
  Tags.DCOM: '20060619',
  Tags.LR: '20151119',
  Tags.IS: '0048-0169 (Linking)',
  Tags.VI: '54',
  Tags.IP: '2',
  Tags.DP: '2006 Apr',
  Tags.TI: 'Comparison of a camera - software system and typical farm management for      detecting oestrus in dairy cattle at pasture.',
  Tags.PG: '73-7',
  Tags.AB: 'AIM: To compare the sensitivity, specificity, predictive values and accuracy of      detection of oestrus using a novel oestrus detection strip (ODS) and a      camera-software device (CSD) with typical farm management practices of visual      observation and use of tail paint in dairy cattle at pasture. METHODS: Dairy cows      (n = 480) in a seasonal-calving herd managed at pasture under typical commercial      conditions in New Zealand were stratified by age, body condition score and days      in milk, then randomly allocated to one of two groups prior to the planned start      of mating (PSM). Tail paint was applied to all cows and oestrus detected by      visual observation of oestrous behaviour and removal of paint, by farm staff. One      group (n = 240) was fitted with ODS and also monitored for signs of oestrus using      a CSD, while the Control group (n = 240) was monitored using tail paint and      visual observations only. Cows detected in oestrus were artificially inseminated      (AI), and pregnancy status determined using rectal palpation and ultrasonography,      51-52 days after the end of a 55-day A period. Results of pregnancy diagnosis      were used to confirm the occurrence of oestrus, and the sensitivity, specificity,      predictive value and accuracy of detection of oestrus compared between oestrus      detection methods. RESULTS: The sensitivity and accuracy of oestrus detection in      the Control group, using visual observation and tail paint, were low. Compared      with the Control group, detection of oestrus using the ODS and CSD resulted in      greater sensitivity (85% vs 78%; p = 0.006), specificity (99.6% vs 98.0%; p <      0.001), positive predictive value (PPV; 88% vs 51%; p < 0.001) and overall      accuracy (99.0% vs 98.0%; p < 0.001). Negative predictive value (NPV) did not      differ significantly between groups (99.4% vs 99.3%; p = 0.28). Pregnancy rate to      first service was higher in the CSD group than in the Control group (72% vs 39%;      p < 0.05). Use of the CSD significantly increased the cumulative proportion of      cows pregnant to AI over the breeding period (p = 0.044). CONCLUSION AND CLINICAL      RELEVANCE: The ODS and CSD was satisfactory for detection of oestrus in seasonal      calving dairy herds grazing on pasture and could improve the sensitivity and      accuracy of detection of oestrus in herds where these are low.',
  Tags.FAU: 'Bailey, D',
  Tags.AU: ['Alawneh JI', 'Williamson NB', 'Bailey D'],
  Tags.AD: 'Institute of Veterinary, Animal and Biomedical Sciences, Massey University,      Private Bag 11222, Palmerston North, New Zealand. ibr_ala@yahoo.co.nz',
  Tags.LA: 'eng',
  Tags.PT: [MeshPublicationType.COMPARATIVE_STUDY, MeshPublicationType.JOURNAL_ARTICLE, ],
  Tags.PL: 'England',
  Tags.TA: 'N Z Vet J',
  Tags.JT: 'New Zealand veterinary journal',
  Tags.JID: '0021406',
  Tags.RN: ['0 (Reagent Strips)'],
  Tags.SB: 'IM',
  Tags.MH: ['Animals', 'Cattle/*physiology', 'Dairying', 'Estrus Detection/*methods/*standards', 'Female', 'Insemination, Artificial/veterinary', 'Predictive Value of Tests', 'Pregnancy', 'Pregnancy Rate', 'Reagent Strips', 'Reproducibility of Results', 'Sensitivity and Specificity', 'Software'],
  Tags.EDAT: '2006/04/06 09:00',
  Tags.MHDA: '2006/06/20 09:00',
  Tags.CRDT: '2006/04/06 09:00',
  Tags.PHST: '2006/04/06 09:00 [entrez]',
  Tags.AID: '10.1080/00480169.2006.36615 [doi]',
  Tags.PST: 'ppublish',
  Tags.SO: 'N Z Vet J. 2006 Apr;54(2):73-7. doi: 10.1080/00480169.2006.36615.',
}
