[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "math_operation"
version = "0.0.0"
authors = [
  { name="Samuel Andrés", email="samuel.andres@yahoo.fr" },
]
description = "Cartography and geodesy formulas."
readme = "README.md"
license = {file = "LICENSE.md"}
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: Public Domain",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",
    "Topic :: Utilities"
]
keywords = ["epsg", "geomatics", "cartography", "geodesy", "projection", "mathematics"]

[project.urls]
"Homepage" = "https://github.com/SamuelAndresPascal/cosmoloj-py/tree/master/unit_simple"
"Documentation" = "http://cosmoloj.com/mkdocs/unit_simple/master"
"Specification" = "http://cosmoloj.com/su"
