.bibliograpy:branch:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^bibliograpy_/

.bibliograpy:tag:
  rules:
    - if: $CI_COMMIT_TAG =~ /^bibliograpy_/

.bibliograpy:branch_tag:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^bibliograpy_/
    - if: $CI_COMMIT_TAG =~ /^bibliograpy_/

conda_env:bibliograpy:
  extends: .conda_env
  variables:
    PACKAGE_NAME: bibliograpy

lint:bibliograpy:
  extends: .lint
  variables:
    PACKAGE_NAME: bibliograpy
  rules:
    - !reference [.lint, rules]
    - !reference [.bibliograpy:branch, rules]
  script:
    - !reference [.lint, script]
    - pylint --rcfile=../pylintrc_strict src/bibliograpy/bibliograpy.py
    - pylint --rcfile=../pylintrc_strict src/bibliograpy/process.py
    - pylint --rcfile=../pylintrc_strict src/bibliograpy/default_symbolizer.py
    - pylint --rcfile=../pylintrc_bibliograpy-src-api src/bibliograpy/api_core.py
    - pylint --rcfile=../pylintrc_bibliograpy-src-api src/bibliograpy/api_bibtex.py
    - pylint --rcfile=../pylintrc_strict src/bibliograpy/api_ris2001.py
    - pylint --rcfile=../pylintrc_strict src/bibliograpy/api_ris2011.py
    - pylint --rcfile=../pylintrc_strict src/bibliograpy/api_refer.py
    - pylint --rcfile=../pylintrc_strict src/bibliograpy/api_endnote.py
    - pylint --rcfile=../pylintrc_strict src/bibliograpy/api_mesh.py
    - pylint --rcfile=../pylintrc_strict src/bibliograpy/api_pubmed.py
    - pylint --rcfile=../pylintrc_strict src/bibliograpy/io_bibtex.py
    - pylint --rcfile=../pylintrc_strict src/bibliograpy/io_ris2001.py
    - pylint --rcfile=../pylintrc_strict src/bibliograpy/io_ris2011.py
    - pylint --rcfile=../pylintrc_strict src/bibliograpy/io_refer.py
    - pylint --rcfile=../pylintrc_strict src/bibliograpy/io_endnote.py
    - pylint --rcfile=../pylintrc_strict src/bibliograpy/io_pubmed.py
    - pylint --rcfile=../pylintrc_strict src/bibliograpy/api_common.py

lint_test:bibliograpy:
  extends: .lint_test
  variables:
    PACKAGE_NAME: bibliograpy
  rules:
    - !reference [.lint_test, rules]
    - !reference [.bibliograpy:branch, rules]
  script:
    - !reference [.lint_test, script]
    - pylint --rcfile=../pylintrc_strict test/example_symbolizer.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_process_bibtex.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_process_ris2001.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_process_ris2011.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_process_refer.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_process_endnote.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_process_pubmed.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_api_core.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_api_bibtex.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_api_ris2001.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_api_mesh.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_api_common.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_io_ris2001.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_io_ris2011.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_io_refer.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_io_endnote.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_io_pubmed.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_ris2011.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_endnote.py
    - pylint --rcfile=../pylintrc_bibliograpy-test test/test_pubmed.py

doc:en:bibliograpy:
  extends: .doc
  variables:
    PACKAGE_NAME: bibliograpy
    LANG: en
  rules:
    - !reference [.doc, rules]
    - !reference [.bibliograpy:branch_tag, rules]

doc:fr:bibliograpy:
  extends: .doc
  variables:
    PACKAGE_NAME: bibliograpy
    LANG: fr
  rules:
    - !reference [.doc, rules]
    - !reference [.bibliograpy:branch_tag, rules]

test:bibliograpy:
  extends: .test
  variables:
    PACKAGE_NAME: bibliograpy
  rules:
    - !reference [.test, rules]
    - !reference [.bibliograpy:branch, rules]

python-version-support:bibliograpy:
  extends: .python-version-support
  variables:
    PACKAGE_NAME: bibliograpy
  rules:
    - !reference [.python-version-support, rules]
    - !reference [.bibliograpy:branch, rules]
  script:
    - !reference [.python-version-support, script]
    - . resources/check_py_version.sh 3.14 || exit 1
    - . resources/check_py_version.sh 3.13 || exit 1
    - . resources/check_py_version.sh 3.12 || exit 1

demo:bibliograpy:
  extends: .demo
  variables:
    PACKAGE_NAME: bibliograpy
  rules:
    - !reference [.demo, rules]
    - !reference [.bibliograpy:branch, rules]
  script:
    - !reference [.demo, script]
    - . preprocess_and_use.sh

pypi-package:bibliograpy:
  extends: .pypi-package
  variables:
    PACKAGE_NAME: bibliograpy
  rules:
    - !reference [.pypi-package, rules]
    - !reference [.bibliograpy:branch_tag, rules]

pypi-publish-test:bibliograpy:
  extends: .pypi-publish-test
  variables:
    PACKAGE_NAME: bibliograpy
  rules:
    - !reference [.bibliograpy:tag, rules]

pypi-publish:bibliograpy:
  extends: .pypi-publish
  variables:
    PACKAGE_NAME: bibliograpy
  rules:
    - !reference [.bibliograpy:tag, rules]

conda-package:bibliograpy:
  stage: conda-package
  rules:
    - if: $CI_COMMIT_TAG =~ /^bibliograpy_/
      when: delayed
      start_in: 5 minutes
  variables:
    DIST_DIR: conda_dist
    PACKAGE: bibliograpy
  script:
    - cd bibliograpy
    - conda env create --yes --file environment_conda_pkg.yml
    - conda activate conda_pkg
    - conda list
    - rm -rf $DIST_DIR/
    - mkdir $DIST_DIR
    - grayskull pypi -o $DIST_DIR $PACKAGE
    - cat $DIST_DIR/$PACKAGE/meta.yaml
    - conda build --numpy=2.0 --channel conda-forge $DIST_DIR/$PACKAGE
  artifacts:
    paths:
      - bibliograpy/$DIST_DIR/*

conda-publish:bibliograpy:
  stage: conda-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^bibliograpy_/
  variables:
    PACKAGE: bibliograpy
  script:
    - cd bibliograpy
    - conda env create --yes --file environment_conda_pkg.yml
    - conda activate conda_pkg
    - conda list
    - VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f 2)
    - anaconda logout
    - anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
    - anaconda upload $CONDA_HOME/conda-bld/noarch/$PACKAGE-$VERSION-py_0.tar.bz2
    - anaconda logout
  environment:
    name: anaconda bibliograpy
    url: https://anaconda.org/cosmoloj/bibliograpy/
