site_name: Bibliograpy
repo_url: https://github.com/SamuelAndresPascal/cosmoloj-py
edit_uri: https://github.com/SamuelAndresPascal/cosmoloj-py/blob/master/bibliograpy/docs
site_description: Bibliograpy documentation site
site_author: Samuel Andrés

strict: true

nav:
  - specification: specification.md
  - bibliograpy:
      - bibliograpy: bibliograpy.md
      - process: bibliograpy_bibtex.md
      - ris_refer: bibliograpy_ris_refer.md
  - API: api.md
  - About: about.md

not_in_nav: |
  /index.md

theme: mkdocs  # readthedocs

plugins:
  - search
  - mkdocstrings
  - bibtex:
      bib_file: bibliograpy.bib
      csl_file: https://raw.githubusercontent.com/citation-style-language/styles/refs/heads/master/bristol-university-press.csl

markdown_extensions:
  - admonition
  - toc
  - footnotes # for bibliography

validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    absolute_links: warn
    unrecognized_links: warn
    anchors: warn
