lint:taxref:
  stage: lint
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    # install deps
    - conda install pandas python-dotenv
    # install tool
    - conda install pylint
    # install deps for pylint to find
    - conda install pytest
    - pip install .
    - conda list
    - pylint --rcfile=../pylintrc taxref.py
    - pylint --rcfile=../pylintrc taxref11.py
    - pylint --rcfile=../pylintrc test.py
    - pylint --rcfile=../pylintrc taxref_test.py

test:taxref:
  stage: test
  allow_failure: true
  script:
    - conda env create --force --file taxref/environment.yml
    - conda install pandas python-dotenv
    - conda install pytest-cov
    - pytest --cov=taxref --junitxml=taxref/report.xml --cov-append taxref
    - pip install .
    - python test.py
  artifacts:
    when: always
    paths:
      - .coverage
      - taxref/.coverage
      - taxref/report.xml
    reports:
      junit: taxref/report.xml
    expire_in: 2 days
