lint:taxref:
  stage: lint
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  variables:
    PYTHONPATH: .
  allow_failure: true
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    # install deps
    - conda install -y pandas python-dotenv
    # install tool
    - conda install -y pylint
    # install deps for pylint to find
    - conda install -y pytest
    - conda list
    - pip install .
    - pylint --rcfile=../pylintrc src
    - pylint --rcfile=../pylintrc test/test.py
    - pylint --rcfile=../pylintrc test/taxref_test.py

test:taxref:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  variables:
    PYTHONPATH: taxref
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    - conda install -y pandas python-dotenv
    - conda install -y pytest-cov
    - pip install .
    - cd ..
    - pytest --cov=taxref --junitxml=taxref/report.xml --cov-append taxref
    - python taxref/test/test.py
  artifacts:
    when: always
    paths:
      - .coverage
      - taxref/report.xml
    reports:
      junit: taxref/report.xml
    expire_in: 2 days

pypi-package:taxref:pypi:
  stage: pypi-package
  rules:
    - if: $CI_COMMIT_TAG =~ /^taxref-/
      when: always
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    - rm -rf dist/
    - sed -i "s#version\ =\ .*\$#version\ =\ \"$TAXREF_VERSION\"#g" pyproject.toml
    - cat pyproject.toml
    - cp ../LICENSE.md .
    - pip install .
    - conda install -y build
    - python -m build
    - ls -l $DIST_DIR
    - conda uninstall -y build
  artifacts:
    paths:
      - taxref/$DIST_DIR/*

pypi-publish:taxref:test_pypi:
  stage: pypi-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^taxref-/
      when: manual
    - when: never
  dependencies:
    - pypi-package:taxref:pypi
  when: manual
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    - conda install -y --update-deps twine
    - python -m twine upload --repository testpypi -u $TEST_PYPI_USERNAME -p $TEST_PYPI_PASSWORD dist/*
    - conda uninstall -y twine
  environment:
    name: test pypi taxref
    url: https://test.pypi.org/project/taxref/

pypi-publish:taxref:pypi:
  stage: pypi-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^taxref-/
      when: manual
    - when: never
  dependencies:
    - pypi-package:taxref:pypi
  when: manual
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    - conda install -y --update-deps twine
    - python -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
    - conda uninstall -y twine
  environment:
    name: pypi taxref
    url: https://pypi.org/project/taxref/

conda-package:taxref:
  stage: conda-package
  rules:
    - if: $CI_COMMIT_TAG =~ /^taxref-/
      when: manual
    - when: never
  variables:
    DIST_DIR: conda_dist
    PACKAGE: taxref
    VERSION: $TAXREF_VERSION
  when: manual
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    - rm -rf $DIST_DIR/
    - mkdir $DIST_DIR
    - conda install -c conda-forge grayskull
    - grayskull pypi -o $DIST_DIR $PACKAGE
    - conda build $DIST_DIR/$PACKAGE
    - anaconda logout
    - anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
    - anaconda upload $CONDA_HOME/conda-bld/noarch/$PACKAGE-$VERSION-py_0.tar.bz2
    - anaconda logout
  artifacts:
    paths:
      - taxref/$DIST_DIR/*
  environment:
    name: anaconda taxref
    url: https://anaconda.org/cosmoloj/taxref/