conda_env:taxref:
  extends: .conda_env
  variables:
    PACKAGE_NAME: taxref

lint:taxref:
  extends: .lint
  variables:
    PACKAGE_NAME: taxref
  script:
    - !reference [.lint, script]
    - pylint --rcfile=../pylintrc_taxref-src src

lint_test:taxref:
  extends: .lint_test
  variables:
    PACKAGE_NAME: taxref
  script:
    - !reference [.lint_test, script]
    - pylint --rcfile=../pylintrc_src test/test.py
    - pylint --rcfile=../pylintrc_src test/taxref_test.py

test:taxref:
  extends: .test
  variables:
    PACKAGE_NAME: taxref

python-version-support:taxref:
  stage: python-version-support
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^taxref_/
  variables:
    PYTHONNOUSERSITE: 1 # shortcuts system python libs installed in ~/.local/lib/python3.x/site-packages
  script:
    - cd taxref
    #- . resources/check_py_version.sh 3.13 || exit 1 doit attendre le support de 3.13 par pandas
    - . resources/check_py_version.sh 3.12 || exit 1
    - . resources/check_py_version.sh 3.11 || exit 1
    - . resources/check_py_version.sh 3.10 || exit 1
    - . resources/check_py_version.sh 3.9 || exit 1
    - . resources/check_py_version.sh 3.8 || exit 1
    - . resources/check_py_version.sh 3.7 || exit 1

pypi-package:taxref:pypi:
  stage: pypi-package
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^taxref_/
    - if: $CI_COMMIT_TAG =~ /^taxref_/
  script:
    - cd taxref
    - conda env create --yes --file environment_pypi_pkg.yml
    - conda activate pypi_pkg
    - conda list
    - rm -rf dist/
    - if [ $CI_COMMIT_TAG ] ; then VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f 2) ; else VERSION=$CI_COMMIT_BRANCH ; fi
    - if [ $CI_COMMIT_TAG ] ; then sed -i "s#version\ =\ \"0.0.0\"\$#version\ =\ \"$VERSION\"#g" pyproject.toml ; fi
    - if [ $CI_COMMIT_TAG ] ; then sed -i "s#\(\"Homepage\" = .*/\)master\(/taxref\)#\1$CI_COMMIT_TAG\2#g" pyproject.toml ; fi
    - sed -i "s#\(\"Documentation\" = .*/\)master#\1$VERSION#g" pyproject.toml
    - cat pyproject.toml
    - cp ../LICENSE.md .
    - pip install .
    - python -m build
    - ls -l $DIST_DIR
  artifacts:
    paths:
      - taxref/$DIST_DIR/*

pypi-publish:taxref:test_pypi:
  stage: pypi-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^taxref_/
  script:
    - cd taxref
    - conda env create --yes --file environment_pypi_publish.yml
    - conda activate pypi_publish
    - conda list
    - python -m twine upload --repository testpypi -u $TEST_PYPI_USERNAME -p $TEST_PYPI_PASSWORD dist/*
  environment:
    name: test pypi taxref
    url: https://test.pypi.org/project/taxref/

pypi-publish:taxref:pypi:
  stage: pypi-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^taxref_/
  script:
    - cd taxref
    - conda env create --yes --file environment_pypi_publish.yml
    - conda activate pypi_publish
    - conda list
    - python -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
  environment:
    name: pypi taxref
    url: https://pypi.org/project/taxref/

conda-package:taxref:
  stage: conda-package
  rules:
    - if: $CI_COMMIT_TAG =~ /^taxref_/
      when: delayed
      start_in: 5 minutes
  variables:
    DIST_DIR: conda_dist
    PACKAGE: taxref
  script:
    - cd taxref
    - conda env create --yes --file environment_conda_publish.yml
    - conda activate conda_publish
    - conda list
    - rm -rf $DIST_DIR/
    - mkdir $DIST_DIR
    - grayskull pypi -o $DIST_DIR $PACKAGE
    - cat $DIST_DIR/$PACKAGE/meta.yaml
    - conda build --numpy=2.0 $DIST_DIR/$PACKAGE
  artifacts:
    paths:
      - taxref/$DIST_DIR/*

conda-publish:taxref:
  stage: conda-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^taxref_/
  variables:
    PACKAGE: taxref
  script:
    - cd taxref
    - conda env create --yes --file environment_conda_publish.yml
    - conda activate conda_publish
    - conda list
    - VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f 2)
    - anaconda logout
    - anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
    - anaconda upload $CONDA_HOME/conda-bld/noarch/$PACKAGE-$VERSION-py_0.tar.bz2
    - anaconda logout
  environment:
    name: anaconda taxref
    url: https://anaconda.org/cosmoloj/taxref/
