lint:taxref:
  stage: lint
  variables:
    PYTHONPATH: .
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    # install deps
    - conda install -y pandas python-dotenv
    # install tool
    - conda install -c conda-forge -y  pylint>3.0.3
    # install deps for pylint to find
    - conda install pytest
    - conda list
    - pylint --rcfile=../pylintrc taxref_common.py
    - pylint --rcfile=../pylintrc taxref11.py
    - pylint --rcfile=../pylintrc test.py
    - pylint --rcfile=../pylintrc taxref_test.py

test:taxref:
  stage: test
  variables:
    PYTHONPATH: taxref
  allow_failure: true
  script:
    - conda env create --force --file taxref/environment.yml
    - conda install -y pandas python-dotenv
    - conda install -y pytest-cov
    - pytest --cov=taxref --junitxml=taxref/report.xml --cov-append taxref
    - python taxref/test.py
  artifacts:
    when: always
    paths:
      - .coverage
      - taxref/report.xml
    reports:
      junit: taxref/report.xml
    expire_in: 2 days

pypi-package:taxref:test_pypi:
  stage: pypi-package
  variables:
    DIST_DIR: test_pypi_dist
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    - rm -rf $DIST_DIR/
    - sed -i "s#version\ =\ .*#version\ =\ \"$TAXREF_VERSION\"#g" pyproject.toml
    - cat pyproject.toml
    - pip install .
    - conda install -c conda-forge build
    - python -m build -o $DIST_DIR
    - ls -l $DIST_DIR
    - conda uninstall -y build
  artifacts:
    paths:
      - taxref/$DIST_DIR/*

pypi-package:taxref:pypi:
  stage: pypi-package
  variables:
    DIST_DIR: dist
  when: manual
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    - rm -rf $DIST_DIR/
    - sed -i "s#version\ =\ .*\$#version\ =\ \"$TAXREF_VERSION\"#g" pyproject.toml
    - cat pyproject.toml
    - pip install .
    - conda install -y build
    - python -m build
    - ls -l $DIST_DIR
    - conda uninstall -y build
  artifacts:
    paths:
      - taxref/$DIST_DIR/*

pypi-publish:taxref:test_pypi:
  stage: pypi-publish
  variables:
    DIST_DIR: test_pypi_dist
  dependencies:
    - pypi-package:taxref:test_pypi
  when: manual
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    - conda install -y --update-deps twine
    - python -m twine upload --repository testpypi -u $TEST_PYPI_USERNAME -p $TEST_PYPI_PASSWORD $DIST_DIR/*
    - conda uninstall -y twine

pypi-publish:taxref:pypi:
  stage: pypi-publish
  dependencies:
    - pypi-package:taxref:pypi
  when: manual
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    - conda install -y --update-deps twine
    - python -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
    - conda uninstall -y twine

conda-package:taxref:
  stage: conda-package
  variables:
    DIST_DIR: conda_dist
    PACKAGE: taxref
    VERSION: $TAXREF_VERSION
  when: manual
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    - rm -rf $DIST_DIR/
    - conda skeleton pypi --pypi-url $PYPI_URL --output-dir $DIST_DIR $PACKAGE
    - conda build $DIST_DIR/$PACKAGE
    - anaconda logout
    - anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
    - anaconda upload $CONDA_HOME/conda-bld/linux-64/$PACKAGE-$VERSION-py311_0.tar.bz2
    - anaconda logout
  artifacts:
    paths:
      - taxref/$DIST_DIR/*
