lint:taxref:
  stage: lint
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    # install tool
    - conda install -y pylint
    - conda list
    - pip install .
    - pylint --rcfile=pylintrc src
    # install deps for pylint to find
    - conda install -y pytest
    # install deps
    - conda install -y pandas python-dotenv
    - pylint --rcfile=../pylintrc test/test.py
    - pylint --rcfile=../pylintrc test/taxref_test.py

test:taxref:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    - conda install -y pandas python-dotenv
    - conda install -y pytest-cov
    - pip install .
    - cd ..
    - pytest --cov=taxref --junitxml=taxref/report.xml --cov-append taxref
    - python taxref/test/test.py
  artifacts:
    when: always
    paths:
      - .coverage
      - taxref/report.xml
    reports:
      junit: taxref/report.xml
    expire_in: 2 days

python-version-support:taxref:
  stage: python-version-support
  rules:
    - if: $CI_COMMIT_TAG == null
  variables:
    PYTHONNOUSERSITE: 1 # shortcuts system python libs installed in ~/.local/lib/python3.x/site-packages
  script:
    - cd taxref
    - . resources/check_py_support.sh

pypi-package:taxref:pypi:
  stage: pypi-package
  rules:
    - if: $CI_COMMIT_TAG =~ /^taxref_/ || $CI_COMMIT_TAG == null
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    - rm -rf dist/
    - if [ $CI_COMMIT_TAG ] ; then VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f 2) ; else VERSION=$CI_COMMIT_BRANCH ; fi
    - if [ $CI_COMMIT_TAG ] ; then sed -i "s#version\ =\ \"0.0.0\"\$#version\ =\ \"$VERSION\"#g" pyproject.toml ; fi
    - if [ $CI_COMMIT_TAG ] ; then sed -i "s#\(\"Homepage\" = .*/\)master\(/taxref\)#\1$CI_COMMIT_TAG\2#g" pyproject.toml ; fi
    - sed -i "s#\(\"Documentation\" = .*/\)master#\1$VERSION#g" pyproject.toml
    - cat pyproject.toml
    - cp ../LICENSE.md .
    - pip install .
    - conda install -y build
    - python -m build
    - ls -l $DIST_DIR
    - conda uninstall -y build
  artifacts:
    paths:
      - taxref/$DIST_DIR/*

pypi-publish:taxref:test_pypi:
  stage: pypi-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^taxref_/
    - when: never
  dependencies:
    - pypi-package:taxref:pypi
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    - conda install -y --update-deps twine
    - python -m twine upload --repository testpypi -u $TEST_PYPI_USERNAME -p $TEST_PYPI_PASSWORD dist/*
    - conda uninstall -y twine
  environment:
    name: test pypi taxref
    url: https://test.pypi.org/project/taxref/

pypi-publish:taxref:pypi:
  stage: pypi-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^taxref_/
    - when: never
  dependencies:
    - pypi-package:taxref:pypi
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    - conda install -y --update-deps twine
    - python -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
    - conda uninstall -y twine
  environment:
    name: pypi taxref
    url: https://pypi.org/project/taxref/

conda-package:taxref:
  stage: conda-package
  rules:
    - if: $CI_COMMIT_TAG =~ /^taxref_/
      when: manual
    - when: never
  variables:
    DIST_DIR: conda_dist
    PACKAGE: taxref
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    - VERSION=$(echo $CI_COMMIT_TAG | cut -d'-' -f 2)
    - rm -rf $DIST_DIR/
    - mkdir $DIST_DIR
    - conda install -c conda-forge grayskull
    - grayskull pypi -o $DIST_DIR $PACKAGE
    - cat $DIST_DIR/$PACKAGE/meta.yaml
    - conda build $DIST_DIR/$PACKAGE
    - anaconda logout
    - anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
    - anaconda upload $CONDA_HOME/conda-bld/noarch/$PACKAGE-$VERSION-py_0.tar.bz2
    - anaconda logout
  artifacts:
    paths:
      - taxref/$DIST_DIR/*
  environment:
    name: anaconda taxref
    url: https://anaconda.org/cosmoloj/taxref/
