lint:taxref:
  stage: lint
  variables:
    PYTHONPATH: .
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    # install deps
    - conda install pandas python-dotenv
    # install tool
    - conda install pylint
    # install deps for pylint to find
    - conda install pytest
    - conda list
    - pylint --rcfile=../pylintrc taxref_common.py
    - pylint --rcfile=../pylintrc taxref11.py
    - pylint --rcfile=../pylintrc test.py
    - pylint --rcfile=../pylintrc taxref_test.py

test:taxref:
  stage: test
  variables:
    PYTHONPATH: taxref
  allow_failure: true
  script:
    - conda env create --force --file taxref/environment.yml
    - conda install pandas python-dotenv
    - conda install pytest-cov
    - pytest --cov=taxref --junitxml=taxref/report.xml --cov-append taxref
    - python taxref/test.py
  artifacts:
    when: always
    paths:
      - .coverage
      - taxref/report.xml
    reports:
      junit: taxref/report.xml
    expire_in: 2 days

pypi-package:taxref:test_pypi:
  stage: pypi-package
  variables:
    DIST_DIR: test_pypi_dist
  script:
    - cd taxref
    - conda env create --force --file environment.yml
    - rm -rf $DIST_DIR/
    - sed -i "s#version\ =\ .*#version\ =\ \"$TAXREF_VERSION\"#g" pyproject.toml
    - cat pyproject.toml
    - pip install .
    - conda install build
    - python -m build -o $DIST_DIR
    - ls -l $DIST_DIR
    - pip uninstall -y build
  artifacts:
    paths:
      - taxref/$DIST_DIR/*
