conda_env:taxref:
  extends: .conda_env
  variables:
    PACKAGE_NAME: taxref

lint:taxref:
  extends: .lint
  variables:
    PACKAGE_NAME: taxref
  script:
    - !reference [.lint, script]
    - pylint --rcfile=../pylintrc_taxref-src src

lint_test:taxref:
  extends: .lint_test
  variables:
    PACKAGE_NAME: taxref
  script:
    - !reference [.lint_test, script]
    - pylint --rcfile=../pylintrc_src test/test.py
    - pylint --rcfile=../pylintrc_src test/taxref_test.py

test:taxref:
  extends: .test
  variables:
    PACKAGE_NAME: taxref

python-version-support:taxref:
  extends: .python-version-support
  variables:
    PACKAGE_NAME: taxref
  script:
    - !reference [.python-version-support, script]
    #- . resources/check_py_version.sh 3.13 || exit 1 doit attendre le support de 3.13 par pandas
    - . resources/check_py_version.sh 3.12 || exit 1
    - . resources/check_py_version.sh 3.11 || exit 1
    - . resources/check_py_version.sh 3.10 || exit 1
    - . resources/check_py_version.sh 3.9 || exit 1
    - . resources/check_py_version.sh 3.8 || exit 1
    - . resources/check_py_version.sh 3.7 || exit 1

pypi-package:taxref:
  extends: .pypi-package
  variables:
    PACKAGE_NAME: taxref

pypi-publish-test:taxref:
  extends: .pypi-publish-test
  variables:
    PACKAGE_NAME: taxref

pypi-publish:taxref:
  extends: .pypi-publish
  variables:
    PACKAGE_NAME: taxref

conda-package:taxref:
  stage: conda-package
  rules:
    - if: $CI_COMMIT_TAG =~ /^taxref_/
      when: delayed
      start_in: 5 minutes
  variables:
    DIST_DIR: conda_dist
    PACKAGE: taxref
  script:
    - cd taxref
    - conda env create --yes --file environment_conda_publish.yml
    - conda activate conda_publish
    - conda list
    - rm -rf $DIST_DIR/
    - mkdir $DIST_DIR
    - grayskull pypi -o $DIST_DIR $PACKAGE
    - cat $DIST_DIR/$PACKAGE/meta.yaml
    - conda build --numpy=2.0 $DIST_DIR/$PACKAGE
  artifacts:
    paths:
      - taxref/$DIST_DIR/*

conda-publish:taxref:
  stage: conda-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^taxref_/
  variables:
    PACKAGE: taxref
  script:
    - cd taxref
    - conda env create --yes --file environment_conda_publish.yml
    - conda activate conda_publish
    - conda list
    - VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f 2)
    - anaconda logout
    - anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
    - anaconda upload $CONDA_HOME/conda-bld/noarch/$PACKAGE-$VERSION-py_0.tar.bz2
    - anaconda logout
  environment:
    name: anaconda taxref
    url: https://anaconda.org/cosmoloj/taxref/
