lint:taxref:
  stage: lint
  script:
    - cd taxref
    - conda env create --force --file environment.dev.yml
    - pylint --rcfile=../pylintrc taxref.py
    - pylint --rcfile=../pylintrc taxref11.py
    - pylint --rcfile=../pylintrc test.py
    - pylint --rcfile=../pylintrc taxref_test.py

test:taxref:
  stage: test
  allow_failure: true
  script:
    - conda env create --force --file taxref/environment.dev.yml
    - pytest --cov=taxref --cov-append --junitxml=report.xml
    - coverage xml
    - python taxref/test.py
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 2 days
