from collections import namedtuple

PdReadCts = namedtuple('PdReadCts', ['sep', 'header', 'index_col', 'dtype', 'na_filter'])

pdReadCts = PdReadCts(sep='\t',
                      header=0,
                      index_col='CD_NOM',
                      dtype={
                          'CD_NOM': 'string'
                      },
                      na_filter=False)

Taxref11 = namedtuple('Taxref11',
                      ['regne',
                       'phylum',
                       'classe',
                       'ordre',
                       'famille',
                       'sous_famille',
                       'tribu',
                       'group1_inpn',
                       'group2_inpn',
                       'cd_nom',
                       'cd_taxsup',
                       'cd_sup',
                       'cd_ref',
                       'rang',
                       'lb_nom',
                       'lb_auteur',
                       'nom_complet',
                       'nom_complet_html',
                       'nom_valide',
                       'nom_vern',
                       'nom_vern_eng',
                       'habitat',
                       'fr',
                       'gf',
                       'mar',
                       'gua',
                       'sm',
                       'sb',
                       'spm',
                       'may',
                       'epa',
                       'reu',
                       'sa',
                       'ta',
                       'taaf',
                       'pf',
                       'nc',
                       'wf',
                       'cli',
                       'url'])
