name: bibliograpy
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - master
      - bibliograpy_*
  schedule:
    - cron: '30 5 * * 0'

jobs:
  envs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: multienv
          python-version: 3.13
          auto-activate-base: false
      - run: conda install -c cosmoloj multienv
      - run: pyenvs lint
      - working-directory: bibliograpy
        run: pyenvs deps
      - uses: actions/upload-artifact@v4
        with:
          name: pylintrc-environments
          path: pylintrc_*
          retention-days: 1
      - uses: actions/upload-artifact@v4
        with:
          name: conda-environments
          path: bibliograpy/environment_*
          retention-days: 1

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    needs: envs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: mv conda-environments/* bibliograpy/
      - run: mv pylintrc-environments/* .
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: lint
          environment-file: bibliograpy/environment_lint.yml
          python-version: 3.13
          auto-activate-base: false
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: bibliograpy
        run: |
          pip install .
          pylint --rcfile=../pylintrc_strict src/bibliograpy/bibliograpy.py
          pylint --rcfile=../pylintrc_strict src/bibliograpy/process.py
          pylint --rcfile=../pylintrc_bibliograpy-src-api src/bibliograpy/api_core.py
          pylint --rcfile=../pylintrc_bibliograpy-src-api src/bibliograpy/api_bibtex.py
          pylint --rcfile=../pylintrc_strict src/bibliograpy/io_bibtex.py
          pylint --rcfile=../pylintrc_strict src/bibliograpy/api_ris2001.py
          pylint --rcfile=../pylintrc_strict src/bibliograpy/api_ris2011.py
          pylint --rcfile=../pylintrc_strict src/bibliograpy/api_refer.py
          pylint --rcfile=../pylintrc_strict src/bibliograpy/io_ris2001.py
          pylint --rcfile=../pylintrc_strict src/bibliograpy/io_ris2011.py
          pylint --rcfile=../pylintrc_strict src/bibliograpy/api_common.py

  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    needs: envs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: mv conda-environments/* bibliograpy/
      - run: mv pylintrc-environments/* .
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: lint_test
          environment-file: bibliograpy/environment_lint_test.yml
          python-version: 3.13
          auto-activate-base: false
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: bibliograpy
        run: |
          pip install .
          pylint --rcfile=../pylintrc_bibliograpy-test test/test_process_bibtex.py
          pylint --rcfile=../pylintrc_bibliograpy-test test/test_process_ris2001.py
          pylint --rcfile=../pylintrc_bibliograpy-test test/test_process_ris2011.py
          pylint --rcfile=../pylintrc_bibliograpy-test test/test_api_core.py
          pylint --rcfile=../pylintrc_bibliograpy-test test/test_api_bibtex.py
          pylint --rcfile=../pylintrc_bibliograpy-test test/test_api_ris2001.py
          pylint --rcfile=../pylintrc_bibliograpy-test test/test_api_common.py
          pylint --rcfile=../pylintrc_bibliograpy-test test/test_io_ris2001.py
          pylint --rcfile=../pylintrc_bibliograpy-test test/test_io_ris2011.py

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    needs: envs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: mv conda-environments/* bibliograpy/
      - run: mv pylintrc-environments/* .
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          environment-file: bibliograpy/environment_test.yml
          python-version: 3.13
          auto-activate-base: false
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: bibliograpy
        run: pip install .
      - run: pytest --cov=bibliograpy --junitxml=bibliograpy/report.xml --cov-append bibliograpy
