name: coordop
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 5 * * 0'

jobs:
  envs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: multienv
          python-version: 3.13
          auto-activate-base: false
      - run: conda install -c cosmoloj multienv
      - run: pyenvs lint
      - working-directory: coordop
        run: pyenvs deps
      - uses: actions/upload-artifact@v4
        with:
          name: pylintrc-environments
          path: pylintrc_*
          retention-days: 1
      - uses: actions/upload-artifact@v4
        with:
          name: conda-environments
          path: coordop/environment_*
          retention-days: 1

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    needs: envs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: mv conda-environments/* coordop/
      - run: mv pylintrc-environments/* .
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: lint
          environment-file: coordop/environment_lint.yml
          python-version: 3.13
          auto-activate-base: false
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: coordop
        run: |
          pip install .
          bibliograpy process --output-dir src/coordop -s SHARED_SCOPE bibliograpy.bib
          pylint --rcfile=../pylintrc_coordop-src --ignore-paths src/coordop/bibliography.py src

  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    needs: envs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: mv conda-environments/* coordop/
      - run: mv pylintrc-environments/* .
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: lint_test
          environment-file: coordop/environment_lint_test.yml
          python-version: 3.13
          auto-activate-base: false
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: coordop
        run: |
          pip install .
          bibliograpy process --output-dir src/coordop -s SHARED_SCOPE bibliograpy.bib
          pylint --rcfile=../pylintrc_test test/projection/*

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    needs: envs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: mv conda-environments/* coordop/
      - run: mv pylintrc-environments/* .
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          environment-file: coordop/environment_test.yml
          python-version: 3.13
          auto-activate-base: false
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: coordop
        run: |
          pip install .
          bibliograpy process --output-dir src/coordop -s SHARED_SCOPE bibliograpy.bib
          pip install .
      - run: pytest --cov=coordop --junitxml=coordop/report.xml --cov-append coordop
