name: coordop
run-name: ${{ github.actor }}

on:
  workflow_run:
    workflows: ["envs"]
    branches: [master]
    types:
      - completed

jobs:

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: lint
          environment-file: coordop/environment_lint.yml
          python-version: 3.12
          auto-activate-base: false
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: coordop
        run: |
          pip install .
          pylint --rcfile=../pylintrc_src src

  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: lint_test
          environment-file: coordop/environment_lint_test.yml
          python-version: 3.12
          auto-activate-base: false
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: coordop
        run: |
          pip install .
          pylint --rcfile=../pylintrc_test test/projection/*

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          environment-file: coordop/environment_test.yml
          python-version: 3.12
          auto-activate-base: false
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: coordop
        run: pip install .
      - run: pytest --cov=coordop --junitxml=coordop/report.xml --cov-append coordop
