name: coord_operation
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 5 * * 0'

jobs:

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: cosmoloj_py
          environment-file: coord_operation/environment.yml
          python-version: 3.12
          auto-activate-base: false
      - run: conda install -y pylint
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: coord_operation
        run: |
          pip install .
          pylint --rcfile=../pylintrc src
          conda install -y pytest
          conda install -y numpy
          pylint --rcfile=../pylintrc-test test/projection/*

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: cosmoloj_py
          environment-file: coord_operation/environment.yml
          python-version: 3.12
          auto-activate-base: false
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: coord_operation
        run: pip install .
      - run: conda install -y numpy
      - run: conda install -y pytest-cov
      - run: pytest --cov=coord_operation --junitxml=coord_operation/report.xml --cov-append coord_operation
