name: learning
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - master

jobs:
  build__hello:
    runs-on: ubuntu-latest
    steps:
      - name: "print stack"
        run: conda --version
      - name: "checkout repository"
        uses: actions/checkout@master
  build__hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "print stack"
        run: conda --version
      - name: "checkout repository"
        uses: actions/checkout@master
