name: multienv
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 5 * * 0'

jobs:
  envs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: multienv
          python-version: 3.13
          auto-activate-base: false
      - run: conda install -c cosmoloj multienv
      - run: pyenvs lint
      - working-directory: multienv
        run: pyenvs deps
      - uses: actions/upload-artifact@v4
        with:
          name: pylintrc-environments
          path: pylintrc_*
          retention-days: 1
      - uses: actions/upload-artifact@v4
        with:
          name: conda-environments
          path: multienv/environment_*
          retention-days: 1

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    needs: envs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: mv conda-environments/* multienv/
      - run: mv pylintrc-environments/* .
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: lint
          environment-file: multienv/environment_lint.yml
          python-version: 3.13
          auto-activate-base: false
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: multienv
        run: |
          pip install .
          pylint --rcfile=../pylintrc_multienv-src src

  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    needs: envs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: mv conda-environments/* multienv/
      - run: mv pylintrc-environments/* .
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: lint_test
          environment-file: multienv/environment_lint_test.yml
          python-version: 3.13
          auto-activate-base: false
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: multienv
        run: |
          pip install .
          pylint --rcfile=../pylintrc_src test/test_pyenvs.py
          pylint --rcfile=../pylintrc_src test/test_pyenvs_info.py
          pylint --rcfile=../pylintrc_src test/test_pyenvs_deps.py
          pylint --rcfile=../pylintrc_src test/test_pyenvs_deps_formatter.py
          pylint --rcfile=../pylintrc_src test/test_pyenvs_deps_input_std.py
          pylint --rcfile=../pylintrc_test test/test_pyenvs_deps_output_conda.py
          pylint --rcfile=../pylintrc_src test/test_pyenvs_deps_output_pip.py
          pylint --rcfile=../pylintrc_src test/test_pyenvs_lint.py
          pylint --rcfile=../pylintrc_src test/test_pyenvs_lint_input_std.py
          pylint --rcfile=../pylintrc_src test/test_pyenvs_lint_formatter.py
          pylint --rcfile=../pylintrc_test test/test_pyenvs_lint_output_pylint.py

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    needs: envs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: mv conda-environments/* multienv/
      - run: mv pylintrc-environments/* .
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          environment-file: multienv/environment_test.yml
          python-version: 3.13
          auto-activate-base: false
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: multienv
        run: pip install .
      - run: pytest --cov=multienv --junitxml=multienv/report.xml --cov-append multienv
