name: simpleunit
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 5 * * 0'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: cosmoloj_py
          environment-file: simpleunit/environment.yml
          python-version: 3.11
          auto-activate-base: false
      - run: conda install -y pylint
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: simpleunit
        run: |
          pip install .
          pylint --rcfile=../pylintrc src
          pylint --rcfile=../pylintrc demo/demo.py
          conda install -y pytest
          pylint --rcfile=../pylintrc test/test.py
          pylint --rcfile=../pylintrc test/unit_simple_test.py
          pylint --rcfile=../pylintrc test/unit_simple_operator_test.py
          pylint --rcfile=../pylintrc test/unit_simple_built_in_test.py

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: cosmoloj_py
          environment-file: simpleunit/environment.yml
          python-version: 3.11
          auto-activate-base: false
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: simpleunit
        run: pip install .
      - run: conda install -y pytest-cov
      - run: pytest --cov=simpleunit --junitxml=simpleunit/report.xml --cov-append simpleunit
      - run: python simpleunit/test/test.py
