name: taxref
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 5 * * 0'

jobs:
  envs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: multienv
          python-version: 3.13
          auto-activate-base: false
      - run: conda install -c cosmoloj multienv
      - run: pyenvs lint
      - working-directory: taxref
        run: pyenvs deps
      - uses: actions/upload-artifact@v4
        with:
          name: pylintrc-environments
          path: pylintrc_*
          retention-days: 1
      - uses: actions/upload-artifact@v4
        with:
          name: conda-environments
          path: taxref/environment_*
          retention-days: 1

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    needs: envs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: mv conda-environments/* taxref/
      - run: mv pylintrc-environments/* .
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: lint
          environment-file: taxref/environment_lint.yml
          python-version: 3.13
          auto-activate-base: false
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: taxref
        run: |
          pip install .
          pylint --rcfile=../pylintrc_taxref-src src

  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    needs: envs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: mv conda-environments/* taxref/
      - run: mv pylintrc-environments/* .
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: lint_test
          environment-file: taxref/environment_lint_test.yml
          python-version: 3.13
          auto-activate-base: false
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: taxref
        run: |
          pip install .
          pylint --rcfile=../pylintrc_src test/test.py
          pylint --rcfile=../pylintrc_src test/taxref_test.py
