name: taxref
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 5 * * 0'

jobs:

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: lint
          environment-file: taxref/environment_lint.yml
          python-version: 3.12
          auto-activate-base: false
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: taxref
        run: |
          pip install .
          pylint --rcfile=pylintrc_src src

  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: lint_test
          environment-file: taxref/environment_lint_test.yml
          python-version: 3.12
          auto-activate-base: false
      - run: |
          conda --version
          python --version
          conda list
      - working-directory: taxref
        run: |
          pip install .
          pylint --rcfile=../pylintrc_src test/test.py
          pylint --rcfile=../pylintrc_src test/taxref_test.py
