name: unit_simple
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - master

jobs:
  build__unit_simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: cosmoloj_py
          environment-file: unit_simple/environment.yml
          python-version: 3.11
          auto-activate-base: false
      - run: cd unit_simple
